export const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icon = name => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
export function codeBlock(code, language='SHELL') {
  return `<div class="code-block"><div class="code-block-bar"><span>${escapeHTML(language)}</span><button class="copy-button" type="button" data-copy-code aria-label="Copy code">${icon('copy')}<span>Copy</span></button></div><pre tabindex="0" role="region" aria-label="${escapeHTML(language)} code example"><code>${escapeHTML(code)}</code></pre></div>`;
}
const note = (title, body) => `<div class="doc-callout"><strong>${title}</strong>${body}</div>`;
const table = (headers, rows) => `<div class="doc-table-wrap" tabindex="0" role="region" aria-label="${escapeHTML(headers.join(', '))} reference table"><table><thead><tr>${headers.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;

export const installCommand = 'curl -fsSL https://rhyvenai.com/install.sh | bash -s -- --containers';

export const docs = [
  {
    id:'getting-started', title:'Install and run Rhyven', nav:'Getting started', icon:'terminal',
    lead:'Install the CLI, terminal marketplace and runtime, then connect your agent and choose apps.',
    body:`<h2>1. Install with one command</h2>${note('Preview release 0.4.0-rc.8','The installer downloads the binary for your system and verifies its release signature and checksum before installation. This preview supports Linux.')}<p>Download the prebuilt binary directly from Rhyven. No GitHub account, repository access or source build is needed. To compile it yourself, see <a href="#docs/open-source">open source and contributing</a>.</p>${codeBlock(installCommand)}<p>This installs the Rhyven executable and starts Docker dependency setup with your approval. Omit <code>--containers</code> if you only need declarative apps. Rust and host Python are not required.</p><p>Supported platforms: Linux x86-64 and ARM64.</p>
    <h2>2. Open the terminal marketplace</h2><p>The default install location is <code>~/.local/bin/rhyven</code>. Open a new terminal so the PATH change takes effect, then run:</p>${codeBlock('rhyven')}<p>Browse apps, review their permissions and install them. <code>Tab</code> switches to Installed. The marketplace refreshes local state every two seconds; <code>u</code> reviews an app update and <code>?</code> explains the controls.</p>
    <h2>3. Connect an agent</h2><p>Select a collection and configure the agent client. This example uses the Codex adapter; see <a href="#docs/connect-an-agent">agent connection</a> for Claude Code, Cursor, VS Code, Cline and generic MCP clients.</p>${codeBlock('rhyven --collection my-project connect --client codex\nrhyven --collection my-project connect --check')}<p>Reload the agent client if required, then ask it to call <code>rhyven_categories()</code> and confirm the collection is <code>my-project</code>.</p>
    <h2>4. Install an app</h2><p>Ask your connected agent to find Work Management, show its permissions and install it after your approval. Or inspect it in a terminal:</p>${codeBlock('rhyven --collection my-project registry-sync rhyven-ai/registry --anonymous\nrhyven --collection my-project inspect rhyven/work-management\nrhyven --collection my-project install rhyven/work-management')}<p>Sync downloads app manifests into the CLI/TUI cache without installing apps or pulling container images. After reviewing the permissions, repeat the install command with <code>--accept-permissions</code>. Agents use the marketplace approval flow and cannot approve their own requests.</p>
    <h2>Check or resume container setup</h2>${codeBlock('rhyven setup --containers --plan\nrhyven setup --containers\nrhyven doctor')}<p>Ubuntu/Debian dependency setup is automated with user approval. Other Linux systems can reuse a compatible existing engine. Python, language servers and other app dependencies are supplied by each container image.</p>
    <h2>Update Rhyven</h2><p>Run the same install command again to get the latest published runtime. Your collections and configuration are retained. App updates inside the TUI update individual apps; they do not update the Rhyven executable.</p>${note('App IDs','New Rhyven apps use the rhyven/ namespace. Existing installations with older IDs keep their own state. Installing a new ID does not migrate records automatically.')}
    <h2>Support</h2><p>For help with installation, agent connections or apps, email <a href="mailto:support@rhyvenai.com">support@rhyvenai.com</a>.</p>`,
  },
  {
    id:'connect-an-agent', title:'Connect an agent', nav:'Connect an agent', icon:'connect',
    lead:'Connect once. Installed apps become discoverable through the same interface, without another MCP server for each app.',
    body:`<h2>Supported setup adapters</h2>${table(['Client','Setup'],[['Codex','<code>connect --client codex</code>'],['Claude Code','<code>connect --client claude</code>'],['Cursor','<code>connect --client cursor</code>'],['VS Code','<code>connect --client vscode</code>'],['Cline','<code>connect --client cline --config /path/to/settings.json</code>'],['Other stdio MCP clients','<code>connect --client generic</code>']])}<p>Prefix these with <code>rhyven --collection my-project</code>. The adapters refer to Rhyven’s own configuration commands; your agent client still needs to load its configuration.</p>${codeBlock('rhyven --collection my-project connect --client cursor --print\nrhyven --collection my-project connect --check')}<p><code>--print</code> shows configuration without applying it. Setup distinguishes configured settings, a verified server and a verified client session. Restart or reload your client, then use discovery to verify the actual session.</p>
    <h2>When an agent launches Rhyven</h2><p>A launch with non-terminal input/output returns JSON connection instructions. <code>rhyven --agent</code> explicitly requests the same information. An interactive terminal launch opens the TUI. The instructions do not install an MCP connection by themselves.</p><p>Give your agent the <a href="#skills/use-rhyven">Use Rhyven skill</a>, or merge the shorter <a href="#skills/use-rhyven/rule">usage rule</a> into its project instructions. Both explain discovery, collection selection, app calls and human approval for marketplace changes.</p>
    <h2>Pin the collection and actor</h2>${codeBlock('rhyven --collection my-project --actor researcher mcp')}<p>This command starts a stdio MCP server. Configure it as the server command in your client. Each agent can use a stable actor label while sharing the same collection. Actor labels are used for audit and inbox routing; they are not authenticated identities.</p>
    <h2>Connect to a shared runtime</h2><p>Run the REST server in the environment that owns the data. Set a strong <code>RHYVEN_SERVE_TOKEN</code> in its environment and forward the token through the client environment.</p>${codeBlock('rhyven --collection my-project serve --port 7421\n\n# In the client environment, with the server token available:\nrhyven mcp --server http://127.0.0.1:7421')}<p>The HTTP endpoint is REST. The MCP bridge speaks stdio to the agent and REST to the shared server. Non-loopback plaintext serving requires explicit configuration; use TLS when exposing a shared endpoint. The server’s collection determines routing.</p>`,
  },
  {
    id:'agent-interface', title:'Use MCP and REST', nav:'The agent interface', icon:'code',
    lead:'Apps describe their capabilities through a machine-readable function manifest and agent-readable guidance.',
    body:`${codeBlock('rhyven_categories()\nrhyven_describe(category)\nrhyven_call(category, function, args)', 'MCP')}<h2>Discover, describe, call</h2><ol><li><strong>Discover:</strong> inspect installed categories and the selected collection.</li><li><strong>Describe:</strong> read an app’s functions, argument schemas, permissions and guidance.</li><li><strong>Call:</strong> invoke the exact declared function with valid arguments.</li></ol><p>A category is a namespaced app ID such as <code>rhyven/work-management</code>, not a subject label such as “productivity.” The runtime validates every call against the installed contract.</p>${codeBlock(JSON.stringify({category:'rhyven/work-management',function:'object_task_create',args:{data:{title:'Verify recovery',due_date:'2026-10-01',labels:['release']},request_id:'release-task-1'}},null,2),'RHYVEN_CALL ARGUMENTS')}
    <h2>Search documents and issues</h2><p>The current source supports literal, case-insensitive keyword search across the fields declared by an app. Labels, typed comparisons and timestamp filters can be combined. Search currently scans scoped records; there is no vector or full-text index.</p>${codeBlock(JSON.stringify({category:'rhyven/project-knowledge',function:'object_note_query',args:{search:'release recovery',current_only:true,where:{labels:{has:'operations'}},order_by:[{field:'$updated_at',direction:'desc'}]}},null,2),'RHYVEN_CALL ARGUMENTS')}<p>For tasks and issues, use <code>object_task_query</code> or <code>object_issue_query</code>. <code>current_only</code> is available on objects that declare supersession. It hides superseded notes before filters and pagination; historical notes remain readable by ID.</p>
    <h2>The same contract over REST</h2>${codeBlock('GET  /categories\nGET  /categories/{publisher}/{app}\nPOST /categories/{publisher}/{app}/functions/{function}', 'REST')}<p>The POST body is the function’s arguments object. REST and local MCP enter the same Rust core. The earlier <code>/apps</code> routes remain for compatibility. Apps do not need custom HTTP routes or MCP implementations.</p>
    <h2>Retries and concurrent edits</h2><p>Updates require the record’s current <code>expected_revision</code>. On a revision conflict, read the record again before deciding whether to retry. Reuse <code>request_id</code> only for identical logical operations. Container timeouts can have uncertain outcomes; inspect state rather than blindly repeating possible side effects.</p>`,
  },
  {
    id:'app-types', title:'App execution types', nav:'App types & engines', icon:'layers',
    lead:'Use the declarative engine for structured behavior, or ship your own executable logic in a container. The agent contract stays the same.',
    body:`${table(['App type','Execution','State'],[['Declarative','Rust interprets objects, actions, rules and expressions. No Docker required.','JSON records in the collection’s SQLite database.'],['On-demand container','One container invocation per action, with a JSON request and result.','App-owned files or databases in persistent /data.'],['Persistent service','A supervised container remains running and accepts framed JSON messages.','App-owned /data, with lifecycle state managed by Rhyven.']])}
    <h2>Declarative capabilities</h2><p>Define objects, fields, relationships, protected fields, allowed transitions, immutable records and named actions. Actions perform a single create, get, query or update. Typed expressions support arithmetic, comparisons, Boolean conditions, string operations and runtime values such as the actor and timestamp.</p><p>These apps are complete installable packages. Adding a conforming app does not require changing Rhyven source. Work Management, Project Knowledge, Error Management, CI Management and Inventory use this path. See the <a href="#docs/declarative-features">complete declarative feature reference</a> for operators, query options, state guarantees and limits.</p><p>Current boundaries: no general scripts, multi-record action transactions, aggregation, automatic scheduling or dependency-readiness evaluation in the declarative engine. CI Management records pipeline state; it does not execute builds.</p>
    <h2>Custom logic in a container</h2><p>Package the language runtime, dependencies and entrypoint in an image. Python, Rust, Go or another language can implement the same JSON contract. The host needs a compatible Docker engine; it does not need a separate Python virtual environment.</p><p>Pin the image to an immutable digest. Declare action inputs and outputs, resource requirements, permissions and optional secrets. Rhyven Repo Documentation Tool demonstrates custom Python logic with language servers.</p>
    <h2>Persistent services</h2><p>Services add readiness, heartbeats, bounded restart policies and explicit start/stop controls. Messaging provides durable agent inboxes through this backend. The app owns durable jobs and background behavior. A persistent service is not automatically an agent scheduler.</p><p>Container apps may also declare objects. Their generic object operations use Rhyven’s database; container actions use the app’s private storage. These are separate state boundaries.</p><p><a href="#docs/services">Read the service lifecycle guide →</a></p>`,
  },
  {
    id:'declarative-features', title:'Declarative app features', nav:'Declarative features', icon:'layers',
    lead:'Build stateful apps with schemas, relationships, calculations and rules. Rhyven executes the behavior and stores the data; the app needs no Docker image or language runtime.',
    body:`<h2>What the engine provides</h2><p>A declarative app is a format-2 JSON package, usually authored as <code>app.json</code>. The Rust engine validates inputs and executes declared operations when an agent or client calls them. Calculations and rules run in the engine; Markdown guidance helps the agent use the app.</p><p>This reference covers the local declarative engine in the current 0.4.0-rc.8 source candidate. Inspect the installed app with <code>rhyven_describe</code> and validate against the runtime and registry validator you will distribute. A newer source feature does not upgrade an older installed binary.</p>
    ${table(['Capability','What you define'],[
      ['Structured records','Object schemas, typed fields, required values, defaults and validation.'],
      ['App behavior','Named create/get/query/update actions, guarded changes, calculations and lifecycle transitions.'],
      ['Discovery and search','Generated function manifests, guidance, equality filters, typed comparisons, keyword search and pagination.'],
      ['App cooperation','Validated record links within an app or to another installed local app in the same collection.'],
      ['Durable operation','SQLite state, revisions, audit events, retry receipts, collection backups and staged upgrades.'],
      ['Distribution','Scaffolding, validation, behavior tests, packaging, marketplace listing and standalone MCP export.']
    ])}

    <h2>Objects, fields and schema validation</h2><p>Declare 1–32 object types. Object, field and action names start with a lowercase letter, use lowercase letters, digits, underscores or hyphens, and have at most 64 characters. Each object contains a closed object schema: <code>additionalProperties: false</code>. Unknown fields and unsupported schema keywords are rejected.</p>
    ${table(['Schema feature','Supported behavior'],[
      ['Types','object, array, string, integer, number and boolean; nested objects and arrays are supported.'],
      ['Object structure','properties, required and additionalProperties: false.'],
      ['Validation and defaults','enum, default and description; defaults fill absent fields during validation.'],
      ['String bounds','minLength and maxLength count characters.'],
      ['Numeric bounds','minimum and maximum are inclusive. Integer bounds remain exact.'],
      ['Arrays','items declares the element schema; maxItems limits the array.'],
      ['Calendar dates','String format: date validates actual YYYY-MM-DD dates, including leap years, from 0001 through 9999.']
    ])}<p>Patches replace explicitly supplied top-level fields. A nested object or array is replaced as a whole; this is not a recursive merge. Missing optional fields are allowed. There is no null type, union type, <code>$ref</code>, regular-expression schema pattern, or arbitrary JSON Schema extension.</p><p>Schema nesting is capped at eight levels. Without explicit limits, arrays allow up to 1,000 items and strings up to 100,000 characters. Package and request size limits still apply. Dates support filtering and sorting; they do not schedule reminders.</p>

    <h2>Record operations and named actions</h2><p>Every installed object gets generic create, get and query functions, plus update for mutable objects. Generated function names include <code>object_task_create</code>, <code>object_task_get</code> and <code>object_task_query</code>. There is no declarative record-delete operation; an app can model archive or retirement state.</p>
    ${table(['Action field','Purpose'],[
      ['description, input','Describe the action and validate its structured argument object.'],
      ['object, operation','Choose one declared object type and one operation: create, get, query or update.'],
      ['set','Map literals or {"$arg":"name"} templates to create data, update fields or query equality filters.'],
      ['id_arg','Select the input carrying a record ID for get/update; defaults to id.'],
      ['guard','Update-only equality checks against the previous record; literals and argument templates are supported.'],
      ['condition','A Boolean expression that must pass before a create or update.'],
      ['expressions','Calculate field values on create/update. A field cannot appear in both set and expressions.']
    ])}<p>An action produces the selected operation's record or query result. Each mutation affects one record. A named query uses its <code>set</code> equality-filter mapping; use the generic object query for the richer search, ordering and pagination options below.</p>

    <h2>Protection, lifecycle rules and relationships</h2><ul><li><strong>Protected fields:</strong> declare <code>protected_fields</code> and defaults. Ordinary creation must keep those defaults; ordinary updates cannot change them. Named actions may change them while still obeying the schema and other rules.</li><li><strong>Lifecycle transitions:</strong> <code>transitions</code> maps each string-enum state to its allowed next states. An absent or empty outgoing list prevents a change from that state. Actions cannot bypass the graph.</li><li><strong>Immutable records:</strong> <code>immutable: true</code> makes an object append-only. All updates, including named update actions, are rejected.</li><li><strong>Relationships:</strong> declare string ID fields with a target <code>object</code> and optionally <code>app</code>. On a local write, each nonempty ID must resolve to a record in that exact installed local app/object in the same collection. An omitted or empty optional ID is unlinked.</li></ul><p>Relationships validate references; they do not automatically fetch targets, join records, traverse dependencies or cascade changes. A task app and a knowledge app can reference each other's records, while an agent coordinates their separate calls. There is no multi-app transaction or cross-collection relationship.</p>

    <h2>Calculations and expression operators</h2><p>An expression is a typed JSON tree. Use <code>{"literal": VALUE}</code>, <code>{"arg":"amount"}</code>, <code>{"field":"quantity"}</code> or <code>{"runtime":"actor"}</code>. Argument and field references address declared top-level values. Previous-record <code>field</code> references are available only during updates; <code>runtime: now</code> returns Unix seconds and <code>runtime: actor</code> returns the caller's runtime actor label.</p>
    ${table(['Operators','Behavior'],[
      ['add, sub, mul','Two numeric operands; integer or floating-point arithmetic.'],
      ['div, mod','div returns a floating-point number; mod returns the signed integer remainder.'],
      ['eq, ne','Equality and inequality; numeric operands compare numerically.'],
      ['lt, le, gt, ge','Numeric ordering or case-sensitive lexical string ordering.'],
      ['and, or, not','Boolean logic; and/or accept 2–16 operands and short-circuit; not takes one.'],
      ['in','Test whether a value is an element of an array.'],
      ['concat','Concatenate 2–16 strings without implicit type conversion.'],
      ['trim, lower, upper','Trim whitespace or perform Unicode case conversion on a string.']
    ])}<p>Use <code>{"op":"sub","args":[{"field":"quantity"},{"arg":"amount"}]}</code> for subtraction. The validator checks types, operator arity and result types. Integer arithmetic is checked signed 64-bit; overflow, zero division, absent referenced values and non-finite results fail. Division cannot be assigned to an integer field. Mixed integer/float operations reject unsafe integer conversion outside ±(2^53−1); floating point is not exact decimal arithmetic.</p><p>Expressions are bounded to 12 nesting levels and 16 KiB of serialized source per tree; operator results have a 100 KB serialized-size limit, and destination field validation still applies. Every assignment sees the same previous record, not another assignment's new value. Runtime time references within an action share one timestamp. Computed fields are stored by the action; they do not recalculate automatically on unrelated edits.</p>

    <h2>Example: a guarded stock withdrawal</h2><p>This complete action definition assumes an <code>item</code> object with integer <code>quantity</code> and <code>changed_at</code>, and string <code>changed_by</code>. Give quantity a default and protect it if only actions should adjust stock. The condition, calculation and timestamps execute inside the engine.</p>
    ${codeBlock(JSON.stringify({description:'Withdraw stock only when sufficient quantity remains',operation:'update',object:'item',input:{type:'object',properties:{id:{type:'string'},expected_revision:{type:'integer',minimum:1},amount:{type:'integer',minimum:1}},required:['id','expected_revision','amount'],additionalProperties:false},condition:{op:'ge',args:[{field:'quantity'},{arg:'amount'}]},expressions:{quantity:{op:'sub',args:[{field:'quantity'},{arg:'amount'}]},changed_at:{runtime:'now'},changed_by:{runtime:'actor'}}},null,2),'ACTION DEFINITION')}

    <h2>Queries, sorting, search and dates</h2>
    ${table(['Query option','Supported behavior'],[
      ['filters','Exact field equality. All specified fields must match.'],
      ['where: eq / ne / in','Typed comparisons on declared fields; in accepts up to 100 candidate values.'],
      ['where: lt / le / gt / ge','Ranges on numbers, integers or strings, including YYYY-MM-DD date strings.'],
      ['where: contains / has','contains is a case-sensitive literal string substring. has tests exact array-element membership.'],
      ['metadata','eq, lt, le, gt and ge on engine-owned created_at / updated_at Unix-second timestamps.'],
      ['search','Available when the object declares search_fields: 1–32 string or string-array field names. Case-insensitive literal keyword matching across those fields.'],
      ['current_only','Available on immutable objects with a declared supersession_field; excludes records referenced by a successor.'],
      ['order_by','Up to three scalar data fields or $created_at / $updated_at, with asc or desc direction. Default direction is asc.'],
      ['limit / offset','Default page size 100, maximum 1,000; offset ranges from 0 to 1,000,000. Results include items, total, offset and limit.']
    ])}<p>Filters and conditions combine with AND. A missing field fails a <code>where</code> condition, even <code>ne</code>. Search accepts 1–32 whitespace-separated keywords, at most 1,000 characters; every keyword must appear somewhere in the declared search fields. It has no regex syntax, stemming, relevance ranking or vector search.</p><p>Sorting happens before pagination. Missing sort fields come last in either direction, with record ID ascending as the tie-breaker. Queries without explicit sorting use ID order. <code>total</code> counts matches before pagination. The engine scans scoped records and filters/sorts them in memory; it does not provide a full-text index or SQL query language.</p>
    ${codeBlock(JSON.stringify({category:'rhyven/work-management',function:'object_issue_query',args:{search:'login',where:{status:{in:['open','blocked']},due_date:{le:'2026-10-01'}},order_by:[{field:'due_date',direction:'asc'}],limit:20,offset:0}},null,2),'RHYVEN_CALL ARGUMENTS')}
    <p>This example needs the Work Management version exposing issue search, blocked status and due dates. Read the installed function schema first.</p>

    <h2>Corrections and current knowledge</h2><p>An immutable object can declare a <code>supersession_field</code> pointing through a same-object local relationship. Create a new record linking to the original instead of rewriting history. With <code>current_only: true</code>, originals referenced by successors are excluded before other filters and pagination, even if the successor does not match the search. Branching corrections may leave multiple current records. Originals remain retrievable by ID and in queries that include history.</p>

    <h2>State, concurrency and retry guarantees</h2><p>Rhyven stores JSON record envelopes in the collection's SQLite database. Each record has an engine-generated ID, app/object identity, revision, data, creation/update timestamps and last actor. Revision starts at 1. Updates require the current <code>expected_revision</code>; on a conflict, read the record again and reassess the change.</p><p>A successful declarative mutation commits its record, audit event and optional request receipt together. Guard, expression or validation failures leave them unchanged. Audit events include the operation, action if used, actor, record, package hash and request ID.</p><p>Use <code>request_id</code> for retryable calls. Within a collection and actor, an identical request returns its saved result; reusing the ID for different arguments fails. IDs are 1–128 bytes. Do not reuse mutation IDs for new work, or read request IDs when a fresh read is intended.</p><p>Each collection has independent installed versions, records, audits and receipts. Identical package bytes are shared in the Rhyven home. Two agents can collaborate through the same collection or authenticated shared server. <code>global</code> is a separate collection, not an inherited overlay. See <a href="#docs/collections">collections and state</a>.</p>

    <h2>Permissions and the agent interface</h2><p>Local declarative apps require <code>state.read</code>; writes additionally require <code>state.write</code>. Install/update permissions are reviewed by the user. Declarative actions cannot execute processes, read host files, access secrets or make network requests. Actor labels support attribution, not authentication or per-user roles.</p><p>The installed schema generates function names and input schemas for <code>rhyven_categories()</code>, <code>rhyven_describe(category)</code> and <code>rhyven_call(category,function,args)</code>. Descriptions include object/action contracts and the app's <code>guide</code> as Markdown. Guidance is content, not a permission grant. Local MCP, the CLI and REST use the same validation and runtime operations; there is no app-specific server to implement.</p><p>Serve the local engine over authenticated REST for user-controlled shared access. Installation alone opens no network port. Standalone MCP export generates an app-specific adapter from the same contract for compatible external clients. See <a href="#docs/agent-interface">the agent interface</a> and <a href="#docs/connect-an-agent">connection setup</a>.</p>

    <h2>Developer tools, tests and packaging</h2><p>The package declares its format, namespaced ID, numeric major.minor.patch version, publisher, description, hosting, permissions, objects, actions, guide and tests. Optional display name, source reference and migration definitions support presentation, provenance and upgrades. An omitted execution configuration uses the declarative driver. The engine supplies storage; app authors do not provision a database.</p>
    ${codeBlock('rhyven app init acme/stock --dir ./stock\nrhyven app validate ./stock\nrhyven app test ./stock\nrhyven app package ./stock --out ./stock.rhyven.json')}
    <p>Behavior tests run sequentially in isolated state. Cases specify <code>operation</code> and <code>args</code>, with dotted-path <code>expect</code> assertions or an expected <code>error</code> code. Use <code>{"$result":"0.id"}</code> to reference a previous result. Validation checks the contract; testing checks declared behavior. Packaging runs the declarative tests before writing the distributable package.</p><p><code>rhyven app publish</code> adds a version to the local catalog. GitHub release upload and registry submission are separate publishing steps. <code>rhyven app export-mcp</code> exports an installed app. These capabilities do not imply independent certification. Use the <a href="#skills/build-rhyven-declarative-app">declarative authoring skill</a> for a complete runnable package and the <a href="#skills/publish-rhyven-app">publishing skill</a> for distribution.</p>

    <h2>Versions, migrations and recovery</h2><p>Compatible additive upgrades can introduce objects, actions and optional fields without defaults. Explicit version-specific migrations can rename fields and fill defaults in existing records. Each migration uses <code>protocol: 1</code>, a source <code>from</code> version, and <code>steps</code> with an object and <code>rename</code>/<code>defaults</code> maps. Every retained record is revalidated before activation.</p><p>Migration-supported lifecycle extensions must preserve existing edges. Existing immutability, relationships and field protection cannot be relaxed through these migrations. Changing drivers/hosting, removing objects or arbitrary code-based transformations is not a declarative migration feature.</p><p>Updates stage the package and state with a recovery archive; an interrupted, uncommitted activation is rolled back on the next runtime operation. Collection backup/restore preserves manifests, state, audit and retry history. Restore uses a new collection. App removal retains state for compatible reinstallation. See <a href="#docs/recovery">backups and updates</a>.</p>

    <h2>Current limits and when to use a container</h2><p>The declarative engine supports records and bounded operations over them. It does not provide scripts, loops, arbitrary native/Python code, external API calls, background jobs, schedules, automatic reminders, multi-record action transactions, SQL joins/aggregation, unique-field constraints or dependency traversal. Expressions do not automatically invoke other apps.</p><p>Use a container action for custom algorithms, parsers, API integrations or other executable logic; use a persistent service for background work. Keep a declarative app when its behavior fits the supported state model and operations. Agents can coordinate either type through the same interface. See <a href="#docs/app-types">execution types</a>.</p>`,
  },
  {
    id:'collections', title:'Collections and app state', nav:'Collections & state', icon:'box',
    lead:'A collection groups installed app versions and their state. Choose the same collection to collaborate, or a different one to isolate projects.',
    body:`${codeBlock('rhyven collection list\nrhyven collection current\nrhyven collection use my-project\nrhyven --collection my-project list')}<p>A missing named collection is created automatically. The initial CLI default is <code>global</code>. Changing the CLI default does not reroute agent connections that are already pinned to a collection.</p>${codeBlock('~/.rhyven/\n  packages/sha256/              # shared immutable app packages\n  registry-cache/               # marketplace metadata\n  collections/\n    global/state.sqlite3\n    my-project/\n      collection.json\n      state.sqlite3\n      services/                # service lifecycle metadata\n      containers/APP_HASH/data/', 'DIRECTORY LAYOUT')}
    <h2>What is shared?</h2><p>Identical app packages are stored once per Rhyven home. Docker also shares image layers. Each collection keeps independent installed versions, records, approvals, audit entries, receipts and container data.</p><p>Two agents on the same machine share knowledge by using the same home and collection. On separate machines, connect them to the same authenticated runtime server. Do not synchronize an active SQLite database between machines as ordinary files.</p>${note('Global is a collection, not an overlay','A project does not implicitly inherit global apps or data. Configure separate connections when you need both scopes. Collections are state boundaries, not per-agent security boundaries.')}
    <h2>The state model</h2><p>The core stores generic JSON record envelopes in SQLite. Each record has an ID, app, object type, revision, data, creation/update timestamps and last actor. Relationships are IDs validated by the runtime. A declarative mutation, its audit event and its retry receipt commit together.</p><p>Container apps own their persistent <code>/data</code> storage. Messaging uses its own SQLite tables for channels, messages, subscriptions, deliveries and receipts. Container state and runtime receipts are not a single atomic transaction.</p>
    <h2>Customize where state lives</h2>${codeBlock('rhyven --home /path/to/rhyven-home --collection my-project list')}<p>You can also set <code>RHYVEN_HOME</code>. Legacy <code>--workspace PATH</code> uses <code>PATH/.rhyven</code> and cannot be combined with <code>--home</code> or <code>--collection</code>. Installation location is a deployment choice; apps keep the same schema.</p>`,
  },
  {
    id:'build-an-app', title:'Build an app', nav:'Build an app', icon:'sliders',
    lead:'Start with the runtime behavior your app needs. Define its contract, add meaningful tests and make it discoverable to any connected agent.',
    body:`<h2>1. Scaffold</h2>${codeBlock('rhyven app init acme/checklist --dir ./checklist\n\n# For executable code or a persistent service instead:\nrhyven app init acme/analyzer --dir ./analyzer --runtime container\nrhyven app init acme/inbox --dir ./inbox --runtime service')}<p>The default is declarative. Edit the generated <code>app.json</code> contract, guidance and tests. A format-2 package declares its name, numeric version, publisher, description, hosting, permissions, objects and actions.</p>
    <h2>2. Describe the state and rules</h2><p>This object fragment defines a validated due date and a protected lifecycle field. The complete scaffold supplies the other required package fields.</p>${codeBlock(JSON.stringify({schema:{type:'object',properties:{title:{type:'string',minLength:1},status:{type:'string',enum:['open','done'],default:'open'},due_date:{type:'string',format:'date'}},required:['title'],additionalProperties:false},protected_fields:['status'],transitions:{status:{open:['done'],done:[]}},search_fields:['title']},null,2),'OBJECT DEFINITION FRAGMENT')}<p>Use named actions to modify protected fields. Keep important invariants in the schema and action rules; guidance helps the agent understand intent but does not enforce permissions or correctness.</p>
    <h2>3. Validate, test and package</h2>${codeBlock('rhyven app validate ./checklist\nrhyven app test ./checklist\nrhyven app package ./checklist --out ./checklist.rhyven.json')}<p>Validation rejects unsupported schema features. Behavior tests run in isolated state. Test successful operations, rejected arguments, revision conflicts and protected transitions. Packaging declarative apps validates and runs their declared tests.</p>
    <h2>4. Supply custom code when needed</h2>${codeBlock('docker build --iidfile /tmp/analyzer-image.id ./analyzer\nrhyven app package ./analyzer \\\n  --image "$(cat /tmp/analyzer-image.id)" \\\n  --out ./analyzer.rhyven.json\nrhyven app test ./analyzer.rhyven.json --allow-container')}<p>A local image ID is suitable for local testing. For another machine to install it, publish the image to an appropriate registry and package its immutable repository digest. Container tests execute app code and require explicit acceptance.</p>
    <h2>5. Install and use it</h2>${codeBlock('rhyven --collection my-project install ./checklist.rhyven.json --accept-permissions')}<p>Run this only after reviewing its requested permissions. Your connected agent can discover <code>acme/checklist</code> immediately through the existing interface.</p>
    <h2>Optional standalone MCP export</h2>${codeBlock('rhyven --collection my-project app export-mcp acme/checklist --out ./checklist-mcp')}<p>Export an installed app for a client that needs app-specific MCP tools. The generated server reuses the same contract and runtime behavior.</p>`,
  },
  {
    id:'publishing', title:'Publish and distribute an app', nav:'Publish & distribute', icon:'branch',
    lead:'The initial marketplace uses GitHub for packages and registry metadata. Customer state and running workloads remain in the user’s environment.',
    body:`<h2>Publishing steps</h2><ol><li>Build a complete app and maintain its source in your repository.</li><li>Validate, test and package it with a compatible Rhyven version.</li><li>Upload the exact package bytes as a GitHub release asset. Container apps also need an accessible image pinned by digest.</li><li>Generate an index entry referencing the repository, asset ID, version, hash and permissions.</li><li>Submit a pull request to the marketplace registry.</li><li>Automated validation and maintainer review check the submission before it is listed.</li></ol>${codeBlock('rhyven app validate ./my-app\nrhyven app test ./my-app\nrhyven app package ./my-app --out ./my-app.rhyven.json\nrhyven registry-entry ./my-app.rhyven.json \\\n  --repository OWNER/REPOSITORY --asset-id ASSET_ID')}
    ${note('Local publishing and GitHub submission are different','<code>rhyven app publish PACKAGE</code> adds an immutable version to the local catalog. It does not create a GitHub release or registry PR. GitHub release upload and submission are separate steps.')}
    <h2>What the registry records</h2><p>Each listing identifies its app, publisher namespace, version, description, repository, package asset, SHA-256, declared permissions, hosting and execution details, and trust level. Namespace ownership is checked against the publishing identity. Versions cannot silently replace existing package bytes.</p>
    <h2>Open-source engine, apps and registry</h2><p>The public registry is <code>rhyven-ai/registry</code>. It contains app listings, packages and registry validation tooling. The Rust engine, CLI, terminal marketplace and protocol adapters are available under Apache-2.0 in <a href="https://github.com/rhyven-ai/rhyven">rhyven-ai/rhyven</a>. Source for the seven Rhyven apps, examples and tests is available under Apache-2.0 in <a href="https://github.com/rhyven-ai/apps">rhyven-ai/apps</a>. The same open-source license covers both the engine and Rhyven apps. Public app discovery and downloads need no GitHub login. Publishing a contribution requires your GitHub identity.</p>
    <h2>Agent discovery and consent</h2>${codeBlock('rhyven registry-refresh rhyven-ai/registry --anonymous')}<p><code>registry-refresh</code> fetches listing metadata and available repository star counts, without downloading app release assets. Agents browse <code>rhyven/marketplace</code>, prepare an install and show the requested permissions and destination before the human approves. The current CLI <code>search</code>, <code>inspect</code> and TUI use the package cache. Run <code>rhyven registry-sync rhyven-ai/registry --anonymous</code> to download manifests for that flow; images are pulled only after installation approval.</p><p>Repository stars are cached popularity metadata, not a certification score. An unavailable count stays unavailable. The website catalog is a curated snapshot; live discovery and repository stars are available through the runtime.</p>`,
  },
  {
    id:'permissions', title:'Permissions and trust', nav:'Permissions & trust', icon:'lock',
    lead:'A package declares what it needs. Installation review shows the user what will run, where its state belongs and which capabilities it requests.',
    body:`<h2>Core permissions</h2>${table(['Permission','Purpose'],[['state.read / state.write','Read and modify local app state; write access also controls the container’s /data mount.'],['container.execute','Execute the app’s declared container image.'],['service.run','Run a persistent container service.'],['network.connect','Enable container bridge networking; this is broad access, not a per-domain firewall.'],['secrets.read','Inject only the explicitly named supported secret variables.'],['app.call','Allow a persistent service’s declared, version-pinned calls into supported peer apps.']])}
    <h2>Container restrictions</h2><p>Container apps use pinned images, a read-only root filesystem, bounded CPU/memory/process resources, action timeouts and a private data directory. Networking is disabled unless requested. Packages cannot supply arbitrary Docker flags, host networking, privileged mode or a Docker socket mount.</p><p>Host capability checks report missing support. Rhyven does not silently remove required restrictions to make an incompatible host pass. The user controls host repair.</p>
    <h2>Approval belongs to the user</h2><p>An agent prepares an install, update or removal request. The review includes the package, permissions, collection, source and available stars. Compatible MCP clients present a human consent prompt. Other clients return a request for the user to approve in a terminal.</p><p>The agent’s function arguments cannot include a self-approval flag. The website does not approve or execute installations.</p>
    <h2>Publisher and certification</h2><p>These seven apps are published by <strong>Rhyven</strong> under the <code>rhyven/</code> namespace. Their certification status is <strong>Unverified</strong>. Publisher identity and independent certification are separate. Hash verification detects changed bytes; it does not establish that the author’s code is safe. Verified publishers, signatures and independent Rhyven certification require further infrastructure.</p>
    <h2>The trusted-group boundary</h2><p>A collection and a shared REST credential define a trusted client environment. Actor labels support attribution and routing, not individual authentication. Descriptions, app guidance, notes and messages are content the agent must treat as untrusted data.</p>`,
  },
  {
    id:'services', title:'Run persistent services', nav:'Persistent services', icon:'pulse',
    lead:'Use a persistent service when an app needs a long-lived process, background work or durable delivery while agents connect and disconnect.',
    body:`<h2>Start the supervisor</h2>${codeBlock('rhyven daemon start\nrhyven --collection my-project service start rhyven/messaging\nrhyven --collection my-project service status rhyven/messaging\nrhyven --collection my-project service logs rhyven/messaging')}<p>Install the app first. Each app has one service instance per collection. A manual start policy needs an explicit start; an on-demand policy can start on first use while the supervisor is available.</p>${codeBlock('rhyven --collection my-project service stop rhyven/messaging\nrhyven --collection my-project service restart rhyven/messaging')}<p>Explicit stop is durable and prevents automatic restart until started again. Readiness, heartbeats, generation fencing, restart limits and resource admission are managed by the runtime. If Docker is unavailable, status reports the problem and recovery preserves the app’s desired state.</p>
    <h2>Messaging: poll, claim, acknowledge</h2><ol><li>Create a channel, then subscribe using a stable actor label.</li><li>Send a message with a unique <code>message_key</code> and optional task/note links. Current subscribers are captured atomically.</li><li>The receiving agent reads its inbox or claims a delivery lease.</li><li>After completing the work, acknowledge the message with its lease token.</li></ol><p>Expired leases make messages available again. Delivery is at least once: receivers use message IDs and stable operation request IDs to deduplicate work. A new claim needs a new request ID; retrying an old claim returns the original result.</p><p>Messages have automatic creation timestamps. An optional <code>available_at</code> schedules when a message becomes visible. There are no outbound webhooks or automatic agent launches in this app.</p>
    <h2>Service authors</h2><p>Use <code>execution.mode: service</code> and protocol <code>rhyven.service/1</code>. The app exchanges newline-delimited JSON over stdin/stdout, reports readiness and responds to heartbeats. Keep stdout for protocol frames and stderr for logs. Write durable data under <code>/data</code> and handle shutdown cleanly.</p><p>App callbacks require explicit category/function/version grants and currently target supported local declarative peers. App writes, callbacks and runtime receipts do not share a distributed transaction.</p>`,
  },
  {
    id:'recovery', title:'Backups and updates', nav:'Backup & updates', icon:'box',
    lead:'Collections are the recovery unit. Capture the package definitions, runtime database and persistent container files together.',
    body:`<h2>Back up a collection</h2>${codeBlock('rhyven backup my-project --out project.rhyven')}<p>The archive includes installed and retained package definitions, SQLite records, audit history, receipts, approval history and regular files under container <code>/data</code>. Persistent services are stopped and fenced before copying. Previously enabled services resume after a successful backup.</p><p>Container image references are included; image layers, environment credentials, OS startup units and machine registry caches are not. The legacy <code>snapshot</code> command is a partial export, not a replacement for full backup.</p>
    <h2>Restore safely</h2>${codeBlock('rhyven restore project.rhyven --collection recovered-project\n\n# For a reviewed archive containing container apps:\nrhyven restore project.rhyven --collection recovered-project --accept-permissions')}<p>Restore uses a new collection and refuses to overwrite existing state. It verifies hashes, paths, database integrity and contracts. Restored services stay stopped until explicitly started. Inspect the restored collection before reconfiguring agents.</p>
    <h2>Update with a recovery point</h2><p>The runtime backs up state, validates a staged package, applies declared migrations and checks retained records before activation. Container migrations and health checks run in staging with restricted access. An interrupted, uncommitted switch is rolled back at the next runtime operation.</p><p>Declarative migrations support field renames and defaults. The current source can extend lifecycle graphs while preserving existing transitions. Driver/hosting changes and incompatible rule changes require a different migration approach.</p>
    <h2>Removal keeps your work</h2>${codeBlock('rhyven --collection my-project remove rhyven/work-management')}<p>Removal hides the app and retains its data and contract for compatible reinstallation. It is not a data-purge command. Collection backups use a streaming format without a fixed total-size cap; sufficient disk space is still required for the archive and staging.</p>`,
  },
  {
    id:'open-source', title:'Open source and contributing', nav:'Open source & license', icon:'code',
    lead:'The engine and Rhyven apps use Apache-2.0. Read the code, build it locally or contribute improvements.',
    body:`<h2>Source repositories</h2><ul><li><a href="https://github.com/rhyven-ai/rhyven">Engine and website</a>: Rust runtime, CLI, terminal marketplace, MCP and REST adapters, tests and documentation.</li><li><a href="https://github.com/rhyven-ai/apps">Rhyven apps</a>: declarative packages, Python container apps, examples and authoring skills.</li><li><a href="https://github.com/rhyven-ai/registry">App registry</a>: searchable metadata, distribution packages and validation tooling.</li></ul>
    <h2>Apache-2.0</h2><p>You can use, modify and distribute the engine and Rhyven apps, including commercially, subject to the <a href="https://github.com/rhyven-ai/rhyven/blob/main/LICENSE">license terms</a>. Retain the license, applicable notices and attribution, and identify modified files when distributing changes. Dependencies retain their own licenses. The license does not give general permission to use Rhyven trademarks or imply endorsement.</p><p>Community publishers choose licenses for their own apps; check each package. Open source does not change where your app data lives: collections remain in your environment.</p>
    <h2>Build the engine</h2><p>Install Rust 1.90 or newer and a C compiler for the bundled SQLite dependency. Then:</p>${codeBlock('git clone https://github.com/rhyven-ai/rhyven.git\ncd rhyven\ncargo build --release --locked --bin rhyven\n./target/release/rhyven')}<p>The current downloadable runtime and registry validator are 0.4.0-rc.8. The engine and binary releases use Apache-2.0.</p>
    <h2>Contribute and inspect notices</h2><p>Follow <a href="https://github.com/rhyven-ai/rhyven/blob/main/CONTRIBUTING.md">the contribution guide</a> for formatting, tests and review. Report vulnerabilities through <a href="https://github.com/rhyven-ai/rhyven/security/advisories/new">private security reporting</a>.</p>${codeBlock('rhyven license\nrhyven license --third-party')}<p>These commands are available in rc.8 and later. Binary releases and standalone exports also include license and dependency notice files.</p>`,
  },
  {
    id:'roadmap' , title:'Current status and planned work', nav:'Status & roadmap', icon:'branch',
    lead:'Planned work includes expanding the declarative app engine and making Rhyven tools easier to use together. Corvid is in progress; Razorback remains under construction.',
    body:`<h2>Available in the current source</h2><ul><li>A Rust CLI, terminal marketplace, package validation and developer commands.</li><li>Declarative apps, container actions and supervised persistent services.</li><li>The three-tool MCP interface, REST and an optional MCP-to-REST bridge.</li><li>Collections, local state, permission review, backup/restore and staged updates.</li><li>Direct binary installation and GitHub-backed app distribution with registry review.</li><li>Work Management and Project Knowledge 0.4.0, with richer lifecycles, keyword search, corrections and dates.</li><li>Rhyven Repo Documentation Tool custom execution and Messaging’s durable local agent inboxes.</li></ul>
    <h2>Preview release boundaries</h2><p>The downloadable runtime and registry validator are <strong>0.4.0-rc.8</strong>. Signed binary downloads are available from <strong>rhyvenai.com</strong>; see <a href="#docs/getting-started">the installation guide</a>. The <a href="https://github.com/rhyven-ai/rhyven">engine source</a> is open under Apache-2.0; you can build the current candidate from source. The public <a href="https://github.com/rhyven-ai/registry">app registry</a> and its matching validator are live. Five declarative apps and earlier releases of Rhyven Repo Documentation Tool and Messaging are publicly installable. The container versions shown in this catalog are newer candidates with publication pending. The earlier public package/image installation and execution passed anonymously on a fresh Linux x86-64 host. Container apps require a compatible Docker engine.</p><p>This preview supports Linux. Physical-device container acceptance, remaining first-time onboarding and rootless-host acceptance are part of the release work. This is not a general-availability announcement.</p>
    <h2>Planned platform improvements</h2><h3>More declarative engine capabilities</h3><p>Expand the built-in operations, expressions and rules so developers can describe more app behavior in their manifests and run it directly in the engine. The aim is to support more useful apps without requiring custom code or a container. The <a href="#docs/declarative-features">declarative feature reference</a> documents what is available today.</p><h3>Smoother integration across Rhyven tools</h3><p>Make it easier to connect Rhyven tools and combine their capabilities in a shared workflow. Improve setup and the handoff of tasks, knowledge and results between apps through the common agent interface and collections. As Corvid develops, use these same app contracts to connect the harness to the marketplace and installed apps.</p><p>These are planned improvements. Scope and release dates have not been finalized.</p>
    <h2>Corvid</h2><p>Corvid is a harness in development: a main agent coordinates focused workers and uses installable apps for shared tasks, knowledge and handoffs. Development is in progress; Corvid is not yet available. The current runtime does not launch or schedule agent workers.</p><p><a href="#corvid">Read about Corvid →</a></p>
    <h2>Razorback</h2><p>Razorback is coming soon. Its capabilities and release timing have not been announced.</p>`,
  }
];
